name: CI intrale-core

on:
  push:
    branches: [ main ]
  repository_dispatch:
jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Download source code
      uses: actions/checkout@v3
    - name: JDK Setup
      uses: actions/setup-java@v2
      with:
          java-version: '11' # The JDK version to make available on the path.
          distribution: 'temurin'
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
    - name: Version definition
      env:
        REL_CORE: ${{ secrets.REL_CORE }}
        EVO_CORE: ${{ secrets.EVO_CORE }}
        REV_CORE: ${{ secrets.REV_CORE }}
      run: |
        echo "REV_CORE=$(($REV_CORE+1))" >> $GITHUB_ENV
        if [[ $REV_CORE > 21 ]]; then
          echo "REV_CORE=0" >> $GITHUB_ENV 
          echo "EVO_CORE=$(($EVO_CORE+1))" >> $GITHUB_ENV
        fi
        if [[ $EVO_CORE > 11 ]]; then
          echo "EVO_CORE=0" >> $GITHUB_ENV 
          echo "REL_CORE=$(($REL_CORE+1))" >> $GITHUB_ENV
        fi
        echo "REL_CORE=$(($REL_CORE))" >> $GITHUB_ENV
        echo "EVO_CORE=$(($EVO_CORE))" >> $GITHUB_ENV
        echo "VER_CORE=${REL_CORE}.${EVO_CORE}.${REV_CORE}" >> $GITHUB_ENV
        echo "VER_CORE_TEXT=${REL_CORE}_${EVO_CORE}_${REV_CORE}" >> $GITHUB_ENV
    - name: Save REL_CORE
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'REL_CORE'
        value: ${{ env.REL_CORE }}
        repository: 'intrale'
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
        org: true
        visibility: 'all'
    - name: Save EVO_CORE
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'EVO_CORE'
        value: ${{ env.EVO_CORE }}
        repository: 'intrale'
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
        org: true
        visibility: 'all'
    - name: Save REV_CORE
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'REV_CORE'
        value: ${{ env.REV_CORE }}
        repository: 'intrale'
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
        org: true
        visibility: 'all'
    - name: Save VER_CORE
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'VER_CORE'
        value: ${{ env.VER_CORE }}
        repository: 'intrale'
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
        org: true   
        visibility: 'all'        
    - name: Deploy to Github Package Registry
      env:
        VER_PARENT: ${{ secrets.VER_PARENT }}
        MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
        MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
      run: |
        sed -i "s/DEV_PARENT/${VER_PARENT}/gi" pom.xml
        sed -i "s/DEV_CORE/${VER_CORE}/gi" pom.xml
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn -e -X deploy
    - name: Tag Branch  
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "VER_${{ env.VER_CORE_TEXT }}"
        message: "VER_${{ env.VER_CORE_TEXT }}"
    - name: Delete old packages
      uses: actions/delete-package-versions@v3
      with:
        owner: 'llarreta'
        repo: 'intrale'
        package-name: 'ar.com.intrale.core'
        min-versions-to-keep: 3
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}              
    - name: Call intrale-commons recompile with new version of core
      run: |
         curl -X POST https://api.github.com/repos/intrale/intrale-commons/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.MAVEN_SERVER_PASSWORD }} \
          --data '{"event_type": "parent_new_version", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'